package ${packageName};

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ${importEntity};
import ${importRepository};
import br.com.anteros.nosql.persistence.session.NoSQLSessionFactory;
import br.com.anteros.nosql.persistence.session.repository.AbstractSimpleRepository;

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

@Repository("${repository}")
public class ${repositoryNameImpl} extends AbstractSimpleRepository<${entityType}, String> implements ${repositoryName} {

	@Autowired
	public ${repositoryNameImpl}(@Qualifier("sessionFactoryNoSQL") NoSQLSessionFactory sessionFactory) {
		super(sessionFactory);
	}

}
