package ${packageName};

import ${importEntity};
import br.com.anteros.nosql.persistence.session.repository.NoSQLRepository;

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

public interface ${resourceName} extends NoSQLRepository<${entityType}, String> {

}
