package ${packageName};

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import ${importEntity};
import ${importService};
import br.com.anteros.nosql.persistence.session.service.NoSQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.nosql.spring.web.resource.AbstractNoSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

@RestController
@RequestMapping(value = "${requestMapping}")
public class ${controller} extends AbstractNoSQLResourceRest<${entityType}, String> {

	@Autowired
	@Lazy
	private ${interfaceService} ${service};

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public NoSQLService<${entityType}, String> getService() {
		return ${service};
	}
	
	@Override
	protected Page<${entityType}> createConcretePage(List<${entityType}> content, PageRequest pageRequest,
			long totalElements) {
		return new Page${entityType}(content, pageRequest, totalElements);
	}

	class Page${entityType} extends PageImpl<${entityType}> {
		public Page${entityType}(List<${entityType}> content) {
			super(content);
		}

		public Page${entityType}(List<${entityType}> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<${entityType}> createConcreteList(List<${entityType}> result) {
		return new List${entityType}(result);
	}
	
	class List${entityType} extends ArrayList<${entityType}>{
		public List${entityType}(Collection<? extends ${entityType}> c) {
			super(c);
		}
	}
}