package ${packageName};

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import ${importEntity};
import ${importService};
import br.com.anteros.nosql.persistence.session.service.NoSQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.nosql.spring.web.resource.AbstractNoSQLResourceRest;

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

@RestController
@RequestMapping(value = "${requestMapping}")
public class ${controller} extends AbstractNoSQLResourceRest<${entityType}, String> {

	@Autowired
	@Lazy
	private ${interfaceService} ${service};

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public NoSQLService<${entityType}, String> getService() {
		return ${service};
	}
}