package ${packageName};

import ${importEntity};
import ${importService};
import br.com.anteros.nosql.spring.mongodb.service.MongoSimpleService;

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

public class ${serviceNameImpl} extends MongoSimpleService<${entityType}, String> implements ${interfaceService} {

}
