package ${packageName};

import br.com.anteros.nosql.persistence.session.service.NoSQLService;
import ${importEntity};

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

public interface ${serviceName} extends NoSQLService<${entityType}, String> {

}
