package ${packageName};

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import ${importEntity};
import ${importService};
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

@RestController
@RequestMapping(value = "${requestMapping}")
public class ${resource} extends AbstractSQLResourceRest<${entityType}, Long> {

	@Autowired
	@Lazy
	private ${interfaceService} ${service};

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<${entityType}, Long> getService() {
		return ${service};
	}
}